### ISSUE TITLE
Backspace key behavior on cell with letter

### ISSUE THREAD

**Issue by mizlan** [jpnance/xw#4]
When the backspace key is on a cell that already has a letter on it, it should delete the one in the current square and not move back. Otherwise, it is impossible to delete the last letter of a word.

**Comment by jpnance** [comment]
Yeah, this is definitely a thing. I've gotten used to just using `-` and `x` to delete characters but you're right that the backspace key needs to be better-supported. I'll take a look in the coming days. Thanks!

**Comment by jpnance** [comment]
Sorry this took so long for me to get to but I think this functionality should work as expected now. Let me know if you notice any quirks or if I got the expected implementation wrong!
